name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Prepare project
        run: |
          ZIP_FILE="VampireDiariesEngine_Standalone_AndroidStudio_Project (1).zip"
          if [ ! -f "$ZIP_FILE" ]; then
            echo "::error::ZIP file '$ZIP_FILE' not found in repo root."
            exit 1
          fi
          mkdir project
          unzip -q "$ZIP_FILE" -d project
          cd project
          chmod +x gradlew || true
          echo "Project contents:"
          ls -la

      - name: Build Debug APK
        run: |
          cd project
          if [ -f "./gradlew" ]; then
            ./gradlew assembleDebug
          else
            echo "::error::gradlew not found, can't build project."
            exit 2
          fi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: project/**/build/outputs/apk/debug/*.apk
