name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Unzip Android project
        run: unzip "VampireDiariesEngine_Standalone_AndroidStudio_Project (1).zip" -d project

      - name: List project structure
        run: ls -R project

      - name: Build Debug APK
        working-directory: project
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: project/app/build/outputs/apk/debug/app-debug.apk
